apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-nginx
spec:
  selector:
    app: k8s-web-to-nginx
  ports:
    - port: 3333
      targetPort: 3000
  type: LoadBalancer
  ---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: k8s-web-to-nginx
    labels:
      app: k8s-web-to-nginx
  spec:
    replicas: 3
    template:
      metadata:
        name: k8s-web-to-nginx
        labels:
          app: k8s-web-to-nginx
      spec:
        containers:
          - name: k8s-web-to-nginx
            image: jackpts/k8s-web-to-nginx
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 3000
            resources:
              limits:
                memory: "128Mi"
                cpu: "250m"
        restartPolicy: Always
    selector:
      matchLabels:
        app: k8s-web-to-nginx
